#!/usr/bin/env python3
"""
把 web-ui/*.html 嵌入對應 workflow 的「Code: 組 HTML」節點。

用法：python3 inject_web_ui.py
跑完會：
- 讀 12-kb-ui.html → 注入 12-folder-organize.json 的「Code: 組 HTML (kb-ui)」
- 讀 06-ai-ui.html → 注入 06-webhook-gemini-file.json 的「Code: 組 HTML (ai-ui)」
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).parent
WORKFLOWS = HERE.parent / "workflows"

INJECTIONS = [
    {
        "html": HERE / "12-kb-ui.html",
        "wf": WORKFLOWS / "12-knowledge-rag.json",
        "node_name": "Code: 組 HTML (kb-ui)",
    },
    {
        "html": HERE / "06-ai-ui.html",
        "wf": WORKFLOWS / "06-webhook-gemini-file.json",
        "node_name": "Code: 組 HTML (ai-ui)",
    },
]


def inject(html_path: Path, wf_path: Path, node_name: str):
    html = html_path.read_text(encoding="utf-8")

    # backtick template 內要 escape 的字元：
    #   \  → \\
    #   `  → \`
    #   ${ → \${
    safe_html = (
        html.replace("\\", "\\\\")
            .replace("`", "\\`")
            .replace("${", "\\${")
    )

    js_code = f"// Auto-generated by inject_web_ui.py — 不要直接改這裡的 HTML，改 web-ui/{html_path.name} 後重 inject\nconst html = `{safe_html}`;\nreturn [{{ json: {{ html }} }}];"

    wf = json.loads(wf_path.read_text(encoding="utf-8"))
    found = False
    for node in wf.get("nodes", []):
        if node.get("name") == node_name:
            node.setdefault("parameters", {})["jsCode"] = js_code
            node["parameters"]["language"] = "javaScript"
            found = True
            break
    if not found:
        raise RuntimeError(f"node '{node_name}' not found in {wf_path.name}")

    wf_path.write_text(json.dumps(wf, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"✓ injected {html_path.name} ({len(html)} chars) → {wf_path.name} [{node_name}]")


def main():
    for inj in INJECTIONS:
        inject(inj["html"], inj["wf"], inj["node_name"])


if __name__ == "__main__":
    main()
